#! /bin/sh

if [ -n "$VIMHOME" -a -n "$GVIMBIN" ] ; then
  "$GVIMBIN" -Nu "$VIMHOME/vimstubs/vimrc" -U \"$VIMHOME/gvimrc\" "$@"
else
  cat <<EOF
To load this shim, run the following command:

  $ source $(cd $(dirname $0) ; pwd)/load

EOF
  exit 1
fi
