#! /bin/sh

if [ -n "$VIMHOME" -a -n "$VIMBIN" ] ; then
  "$VIMBIN" -Nu "$VIMHOME/vimrc" --cmd "let &rtp = substitute(&rtp, \"$HOME/.vim\", \"$VIMHOME\", \"g\")" "$@"
else
  cat <<EOF
To load this shim, run the following command:

  $ source $(cd $(dirname $0) ; pwd)/load

EOF
  exit 1
fi
